version: '3'

services:
  php:
    build:
      context: docker/php
    restart: always
    environment:
      HISTFILE: /root/history/.history
      ENV: /root/.bashrc
    volumes:
      - .:/var/www/html:cached
      - php_socket:/var/run/php
      - php_history:/root/history

  nginx:
    image: nginx:1.24-alpine3.17
    restart: always
    depends_on:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public/:/var/www/html/public:ro
      - php_socket:/var/run/php
    ports:
      - '8080:80'

  db:
    image: postgres:16.2-alpine3.19
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db/entrypoint:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.5
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    depends_on:
      - db
    volumes:
      - ./db/pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"

volumes:
  php_history: ~
  php_socket: ~
